### ISSUE TITLE
Video: For expert - What is Fountain Marketplace

### ISSUE THREAD

**Issue by apatzer** [askdavinci/marketing#1]
See askdavinci/expert#2221 for context

Similar to the expert video we have now (which could be sufficient), but re-edited with new UI, and across all categories of knowledge (not just Home & Garden).

Fountain Marketplace
• Get new business when questions match your skills.
• We match on skill relevance, location & rating
• Answer quickly, each question is sent to multiple experts and is usual gone in under 60 seconds.
• You must first be approved by Fountain before we send any matches to you. This requires a 15 minute interview M-F 9a - 6p PT inside the Fountain app.
[Video]

**Comment by slangille** [comment]
This is being combined with #2
