### ISSUE TITLE
Youtuber out-reach Fashion/Style

### ISSUE THREAD

**Issue by byjess** [askdavinci/marketing#10]
I put together a list of Fashion/Style Youtubers... it skews heavily towards makeup with a young demo.  I need to find some older youtubers that better fit with our demo.

https://docs.google.com/a/fountain.com/spreadsheets/d/12IpK9Nom5xA28f2jnEEEo_yCM-gkYheRtuz3BM9DF5g/edit#gid=1352872763

I already emailed http://www.melroseandpark.com/ since they rep a bunch of them and will see what their prices are.

Once we have a good list, I'll write up an email and start contacting them.

**Comment by apatzer** [comment]
@byjess See #11 for the kind of messaging you might use.

**Comment by byjess** [comment]
@slangille , Melrose and Park wants to know our budget for this.  Im curious as well.  Apparently there is a sponsorship fee for promotions.

**Comment by byjess** [comment]
Here is my template.


Hey Heidi, 

I came across your YT channel and had to reach out.  I’m the head of marketing at Fountain.com which is an app that connects people to experts.  We started with home and garden but are expanding rapidly.

Fashion and style is our text target and this is clearly something you are an expert in.  I wanted to see if there was a possible business opportunity between you and us.

We are looking for two things.  You would become a fashion and style expert and users could call you for help.  You set your own price, up to $100 an hour.  You could put your custom Fountain URL in a YT annotation.  A great way for some of your super fans to get the full Heidi experience.

But our broader goal is in your ability as an influencer in the YT community.  We would love for you to do a video that promotes Fountain to your users.  I suspect that a lot of your viewers are probably fashion experts themselves and this could be a great way for them to earn some extra money as they certainly don’t have the large audience you have.

We are really looking for an authentic promotion so if you don’t love Fountain and think its a good fit, it probably won’t work.  We absolutely do not want you to compromise the integrity you have built. But if you are interested I’d love to tell you a bit more about how it works and possibly work out a deal.

Please let me know,

Stew Langille
Cheif Marketing Officer
Fountain.com

p.s. This isn’t some affiliate thing.  We are hoping to pay you outright.

**Comment by slangille** [comment]
email to be finalized here and sent tomorrow: https://docs.google.com/document/d/11IS70uieKMQJBq1d35kbWRaANXIe30S3HHyT0C0Q-r4/edit

**Comment by slangille** [comment]
Rolling this up into #11
