### ISSUE TITLE
Sign up 50-100 Twitter experts across a wide variety of categories

### ISSUE THREAD

**Issue by apatzer** [askdavinci/marketing#12]
Part of #8 and similar to #11 

Reach out to Twitter users who have a following in Home & Garden, Style, Cooking, Entrepreneurial or Marketing Advice, and get 50-100 of them to trial Distributed Fountain.

Vera has a great list at https://docs.google.com/a/fountain.com/spreadsheets/d/12IpK9Nom5xA28f2jnEEEo_yCM-gkYheRtuz3BM9DF5g/edit#gid=1715245890

See the "Key Messaging" section of #11

**Comment by apatzer** [comment]
Let's look at #11

**Comment by slangille** [comment]
rolling this task into: https://github.com/askdavinci/marketing/issues/11
