### ISSUE TITLE
The Ultimate Guide to Online Garden Resources

### ISSUE THREAD

**Issue by byjess** [askdavinci/marketing#16]
Its currently in coscheduler for next week, needs some images, to be done by me.  The last of our big garden pieces.  Will work with Grayling to promote.

**Comment by byjess** [comment]
Draft, set to run tomorrow but may push to Thursday. http://blog.fountain.com/2015/04/online-gardening-resources/?preview=true&preview_id=1667&preview_nonce=f6114f250b&post_format=standard

**Comment by dkohreidze** [comment]
@byjess This post is live. Can we close this issue?

**Comment by byjess** [comment]
Closed. Grayling is away of the post.
