### ISSUE TITLE
FB promotion of reddit interview blog posts.

### ISSUE THREAD

**Issue by byjess** [askdavinci/marketing#25]
The glow resin table blog post is doing quite well on Facebook. 3,500+ pageviews, all from FB.  We need to do some FB promotion of some of the other reddit interview posts. @vera

**Comment by slangille** [comment]
Great, Vera I labeled as a P1 - this is the highest priority so lets take advantage of this post

**Comment by dkohreidze** [comment]
![screen shot 2015-04-09 at 1 52 47 pm](https://cloud.githubusercontent.com/assets/1936866/7076659/c15aca26-debf-11e4-8029-94f4717881ae.png)

**Comment by slangille** [comment]
@apatzer fyi Good example of low cost content driving social leads and engagement

**Comment by chungdiya** [comment]
Hi all, it was a bit difficult to post the results here so I've included it here in this Evernote: https://www.evernote.com/l/AH0bN10nVaVPVZLQFQ5hOTVG-FrX-T_zbL4

Essentially, content that contained some sort of novelty worked really well compared to those that were less exotic.
