### ISSUE TITLE
Referral source

### ISSUE THREAD

**Issue by slangille** [askdavinci/marketing#29]
@dkohreidze in top referrals - Google is listed as #1 over the past month; however there are no details on this traffic. Do u have an idea on source? 
![screen shot 2015-04-09 at 4 06 47 pm](https://cloud.githubusercontent.com/assets/9372013/7078890/a6ad4e84-ded2-11e4-821b-19479bb59197.png)

**Comment by dkohreidze** [comment]
This is Lowe's paid ad traffic. You can see that if you change the primary dimension to 
"Landing Page", see [here](https://www.google.com/analytics/web/?authuser=0#report/acquisition-channels/a55524708w88721510p92166812/%3Fexplorer-table.plotKeys%3D%5B%5D%26_r.drilldown%3Danalytics.trafficChannel%3AReferral%2Canalytics.source%3Agoogle%26explorer-segmentExplorer.segmentId%3Danalytics.landingPagePath/).

**Comment by slangille** [comment]
Can you change the attribution, it hurts our ability to analyze the data.

**Comment by dkohreidze** [comment]
I figured it would be best if we just grouped all the traffic Lowe's is sending us into it's own channel. So moving forward, you'll see a new Channel in the Traffic Sources that will capture all the traffic from Lowe's.

![screen shot 2015-04-10 at 1 10 15 pm](https://cloud.githubusercontent.com/assets/1936866/7092885/f8fd683a-df82-11e4-9db3-0acc715829ea.png)
