### ISSUE TITLE
Brand name for "Distributed Fountain"

### ISSUE THREAD

**Issue by apatzer** [askdavinci/marketing#30]
Ideas?

Huddle
Your Time
Private Consult
My Fountain
Fountain Consult
Private Session
Fountain Session
Direct Connect

**Comment by kristentucker** [comment]
Fountain Direct

On Fri, Apr 10, 2015 at 3:19 PM, Aaron Patzer <notifications@github.com>
wrote:

> Ideas?
>
> Huddle
> Your Time
> Private Consult
> My Fountain
> Fountain Consult
> Private Session
> Fountain Session
> Direct Connect
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/askdavinci/marketing/issues/30>.
>



-- 
Kristen Tucker
Head of Business Development & Community, Fountain
799 Market St, 8th Floor San Francisco, CA 94103
@askFountain @tuckerkristen
fountain.com

**Comment by smannfountain** [comment]
+1 @ Fountain Direct

**Comment by jeansini** [comment]
huddle
-- 
Jean Sini ◆ Cofounder + CTO ◆ Fountain
799 Market Street, 8th Floor, San Francisco, CA 94103
www.fountain.com ◆ jean@fountain.com ◆ +1(650)224-3017

**Comment by apatzer** [comment]
Informal survey of friends says it should be either "Fountain Direct" or "Fountain Huddle"

**Comment by byjess** [comment]
When I hear Fountain Direct, it makes me think of Tiger Direct, or Energy Direct, or any of the massive faceless companies that ship stuff "direct".  The word is quite cold, stern, and unfriendly.  It's also efficient, fast, and forceful.  It might work well for for business focused verticals (technology, legal) but doesn't feel like a good fit for parenting, education, cooking, style, arts, relationships.  I can't see anyone under 35 promoting something called "Fountain Direct".

On the flip side, "Huddle is better suited to those more personal verticals but less suited to the business ones, like legal.  It's also a younger word, and I could see the under 35 set, espeically youtubers promoting their "Fountain Huddle".

Huddle sounds like an offering from a new startup, and Direct sounds like an offering from an F500 company.

This is just my opinion.

**Comment by taylorleese** [comment]
I tend to agree with @byjess and I prefer Huddle when given the choice of Direct or Huddle. 

Here are a couple more in case we're still brainstorming:
* Fountain Dialogue
* Fountain Flow
* Fountain Collab

**Comment by smannfountain** [comment]
by definition both the verb and noun huddle means 'crowd' , but this is 1 on 1.

**Comment by kristentucker** [comment]
+1 the word huddle feels really non-intuitive to me

On Tue, Apr 14, 2015 at 9:15 AM, Stephen <notifications@github.com> wrote:

> by definition both the verb and noun huddle means 'crowd' , but this is 1
> on 1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/askdavinci/marketing/issues/30#issuecomment-92942726>.
>



-- 
Kristen Tucker
Head of Business Development & Community, Fountain
799 Market St, 8th Floor San Francisco, CA 94103
@askFountain @tuckerkristen
fountain.com

**Comment by slangille** [comment]
We came to a decision on "My Fountain". It's less dramatic than other options; however, this is on purpose. We want to focus on building the core Fountain brand. Also, this will personalize and message directly to the experts/distribution partners - who are our targets for this launch.
