### ISSUE TITLE
Provide Google Analytics access to Lowe's ad rep

### ISSUE THREAD

**Issue by dkohreidze** [askdavinci/marketing#33]
We are in need of linking our Google Analytics account to the Lowe's paid ad team's AdWords account, in order to get better conversion data on ad performance.

To do this we need to grant Edit permissions on our Google Analytics to their AdWords account admin. After we complete the link, we're able to remove them from our Analytics account. However, keep in mind for that short period of time they will be able to see all of our data.

@apatzer Any issues with doing this?

CC @kristentucker @slangille

**Comment by slangille** [comment]
@apatzer the question is whether we want Lowes to see our analytics, it will only be for a short while, but  we need to recognize that they will see things like our traffic, conversion, referrals, for a short time. You are closer to the relationship so I want you to be aware.
