### ISSUE TITLE
Retargeting campaign for Lowes users

### ISSUE THREAD

**Issue by dkohreidze** [askdavinci/marketing#38]
$500 budget

**Comment by slangille** [comment]
Great @apatzer we are testing the value of Lowe's visitors who come to the site but don't sign up - maybe they were almost ready to sign up - by putting retargeting ads in front of them we can gauge level of interest. We will run a $500 test and see.

**Comment by dkohreidze** [comment]
Retargeting campaign is live. Using branded display ads, directing users to https://www.fountain.com/lowes. Impressions capped at 2 per day.

Ad spend is $20/day capped at $500. Will make adjustments accordingly.
