### ISSUE TITLE
Create 3 display ads for Lowe's online classes page

### ISSUE THREAD

**Issue by dkohreidze** [askdavinci/marketing#39]
Display ad will exist [here.](http://www.lowes.com/en_us/l/nbd/craftsy.html?cm_mmc=vanity_NBD-_-NBD-_-NBD-_-Craftsy_LP_DT)

The dimensions of the ad should be the same width as the top image but roughly 1/4 of the height.

Each ad should have different images/messaging.

CC: @slangille

**Comment by slangille** [comment]
Jess can we have this by next Wednesday? thx

**Comment by byjess** [comment]
So 940 x 86 then.

Are the ads linking to Fountain.com ?  Are they advertising anything specifically other an Fountain.com ?

**Comment by dkohreidze** [comment]
Yes, ads will link to fountain.com/lowes.

**Comment by dkohreidze** [comment]
@byjess We have a call to review with Lowe's on Wednesday @ 10:30am PST. We'll need these before then, please.

**Comment by byjess** [comment]
![fountainlowes2](https://cloud.githubusercontent.com/assets/1053369/7257505/2afddb4a-e824-11e4-86bf-4199dc022a2b.jpg)
![fountainlowes3](https://cloud.githubusercontent.com/assets/1053369/7257506/2afe6c7c-e824-11e4-97aa-3a473d30cda5.jpg)
![fountainlowes1](https://cloud.githubusercontent.com/assets/1053369/7257504/2afcdd76-e824-11e4-8b03-46888db8693a.jpg)

**Comment by apatzer** [comment]
@byjess Nice!

**Comment by dkohreidze** [comment]
These look great Jess. 

Will you send over another version of each where the App Store download button is replaced with a "Learn More" or "Get Started" button?

**Comment by byjess** [comment]
![2fountainlowes1](https://cloud.githubusercontent.com/assets/1053369/7258030/e51517ca-e827-11e4-9906-369d74d28365.jpg)
![2fountainlowes2](https://cloud.githubusercontent.com/assets/1053369/7258032/e51a8e62-e827-11e4-9d12-db1ffa203477.jpg)
![2fountainlowes3](https://cloud.githubusercontent.com/assets/1053369/7258031/e5163664-e827-11e4-9531-277684699503.jpg)

**Comment by byjess** [comment]
Fixed a typo in these.
![fountainlowes3](https://cloud.githubusercontent.com/assets/1053369/7258095/3b3cf186-e828-11e4-88aa-d3024db1b835.jpg)
![2fountainlowes3](https://cloud.githubusercontent.com/assets/1053369/7258096/3b3f2e6a-e828-11e4-9698-719f96924fd2.jpg)

**Comment by slangille** [comment]
Thanks Jess, I approve
