### ISSUE TITLE
Messaging for Web + Distributed Fountain Launch

### ISSUE THREAD

**Issue by apatzer** [askdavinci/marketing#6]
Headline:  Everyone can be a freelancer in 3-minutes

Fountain is launching @usernames, like Fountain.com/aaron (Founder & CEO) and Fountain.com/jean (Founder & CTO), which allow consumers to directly video chat with that expert.  By utilizing the open standard WebRTC, no download is required by consumers*, making the system easy and seamless.

For the freelancers & consultants of the world, that means you can setup Fountain.com/YourName and both existing and new clients can audio or video chat with you, exchange and draw on photos, and message back-and-forth at whatever rate you choose: $100 / hour or even free.

One Fountain general contractor, Fountain/JConstruction shares the URL on his business cards so that he can provide free estimates for potential clients.  With no download on the new client side required, they can walk John through their kitchen remodel without him having to drive across town.  It's the ultimate way to qualify business leads.

Another Fountain veterinarian, Dr. Convery, has been testing the system with her canine patients in upper Michigan, where drive times can be lengthy.  Rather than bring a dog in to the clinic, Dr. Convery is able to use Fountain's video chat to assess her canine patients remotely at a rate of just $10.  Sometimes an in-person exam is still needed, but for more minor issues, a remote interaction serves her patients well without the drive.

Last, stylist Anna, who has 50,000+ followers to her YouTube channel "LailaLov", gets dozens of questions from her devoted followers every day.  Now, she can offer a 1-on-1 interaction with them, for which she charges $15 per 15 minutes, opening up a new stream of revenue for her expertise.

This is a system Fountain's Home & Garden experts have been asking for over the past few months, as they wanted to work with their own clients using Fountain's powerful mobile (and now web) based video chat system.  It's like being able to charge for Skype or Facetime, but across any platform, with Fountain handling time keeping and billing across the English speaking world.  Having a persistent, easy to remember URL like Fountain.com/aaron makes it possible for everyone to earn a living as a freelancer or consultant.

* No download required for WebRTC compatible browsers: desktop Chrome & Firefox, and mobile Chrome on Android.

**Comment by apatzer** [comment]
@kristentucker @slangille Look at the 3-examples I provide in this mock "press release".  We need to actually get a few experts using the system as we describe above to make this super powerful.

@byjess A video showing best practices or how-to on embedding your Fountain/UserName on YouTube, in your Gmail email signature might be useful.

**Comment by apatzer** [comment]
@slangille @byjess Been thinking more about a positioning like:  "Share your knowledge with the world, 1-on-1" rather than freelancing or consulting.

You can be someone's go-to "guy" for a particular area of knowledge.
Like having your own 1-800 number.

**Comment by byjess** [comment]
@apatzer Absolutely.  Being someones "guy" is to be needed.  People want to be needed, especially when they have something of value to give.

The 800 number is tricky, because its supposed to be free.  The 900 number would be more apt, but I don't think anything good is associated with 900 numbers.

**Comment by kristentucker** [comment]
love love love  "Share your knowledge with the world, 1-on-1" so much more
than freelancing/consulting. love go-to guy

On Tue, Apr 14, 2015 at 3:17 PM, byjess <notifications@github.com> wrote:

> @apatzer <https://github.com/apatzer> Absolutely. Being someones "guy" is
> to be needed. People want to be needed, especially when they have something
> of value to give.
>
> The 800 number is tricky, because its supposed to be free. The 900 number
> would be more apt, but I don't think anything good is associated with 900
> numbers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/askdavinci/marketing/issues/6#issuecomment-93089277>.
>



-- 
Kristen Tucker
Head of Business Development & Community, Fountain
799 Market St, 8th Floor San Francisco, CA 94103
@askFountain @tuckerkristen
fountain.com

**Comment by apatzer** [comment]
"Put your idle wisdom to work"

Inspired by a conversation with Relay Rides CEO.  They tested two messages: "Make $1000s renting your car" and "Put your idle car to work".  The later was 3-5x more effectively, because people were more motivated by not wanting to waste what they had than make an incremental bit of money (even though they did in the end).

We all have knowledge, often outside our day job, that we're passionate about and like to share.  Maybe we shouldn't let that idle wisdom go to waste.

**Comment by taylorleese** [comment]
@aaron Love it.

**Comment by byjess** [comment]
Thats smart.  The more we can get away from the rationality of dollars and financial transactions the better.  Cars are tangible and quantifiable where as wisdom is certainly not.  I don't think people will have any idea how to quantify or value their wisdom to start so that aspect should come last in any conversation.

A framework would be:

1. You have value (to other people)
2. Your value is idle/unused.
3. Numbers, details, features, figures....

If we can sell them on the first two, the third will just be used to rationalize the decision they have already made.

**Comment by jeansini** [comment]
love that angle.

how about going all the way to a colloquial expression like “be the go-to guy”, except with something less gender-biased? that really brings up, almost visually, the notion of 1-on-1 in a concrete way.

“share your knowledge with the world, 1-on-1” is a bit more abstract. if you don’t know about fountain, we still have a lot of explaining / backpedaling to do: no, you are not going to have to blog, or edit a wiki, etc. 

To Jess’ point, “idle wisdom” doesn’t resonate quite as much as “idle car” for me. maybe it’s just the choice of the “idle” word. can we hijack a popular expression?

e.g. heroes are unsung: doesn’t everyone want to be someone “sung" hero? "finally, be someone’s sung hero."
e.g. wisdom wasted on the old: don’t let your wisdom go to waste? /  or: "wisdom to spare? Put it to work."

-- 
Jean Sini ◆ Cofounder + CTO ◆ Fountain
799 Market Street, 8th Floor, San Francisco, CA 94103
www.fountain.com ◆ jean@fountain.com ◆ +1(650)224-3017

**Comment by slangille** [comment]
I think sharing is key here: share your passion, share your knowledge. Having meaningful conversations with others like you - you both learn. 

Putting knowledge to work is too literal for our messaging but I like it as a implicit point.

**Comment by slangille** [comment]
Here is the messaging that @byjess and I settled on. Name of distributed Fountain is "My Fountain". 

https://docs.google.com/document/d/114csc3EacpPvbE3C6wP0yB9S6rcIINW0bYKXYiqrJek/edit
